# Generated by Django 3.0.8 on 2020-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
