# Generated by Django 3.0.8 on 2020-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_crawledlinks_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledlinks',
            name='reschedule',
            field=models.IntegerField(default=3),
        ),
    ]
