# Generated by Django 3.0.8 on 2020-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_crawledlinks_reschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='link',
            name='scrape_data',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
