# Generated by Django 3.0.8 on 2020-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20200727_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/static/dummyuser.jpg', null=True, upload_to='profile_images'),
        ),
    ]
