# Generated by Django 3.0.8 on 2020-08-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_userprofile_recent_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('screen_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('tweet_url', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('hashtags', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=30)),
                ('retweets', models.CharField(max_length=30)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Keyword')),
            ],
        ),
    ]
