# Generated by Django 3.0.8 on 2020-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescrapedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=250)),
                ('scrape_data', models.TextField(blank=True, max_length=3000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=250)),
                ('scrape_data', models.TextField(blank=True, max_length=3000)),
                ('schedule_day', models.IntegerField(default=3)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
