# Generated by Django 3.0.8 on 2020-07-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescrapedlink',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescrapedlink',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
